server:
  port: 8000
  shutdown: graceful
  servlet:
    context-path: '/api'

spring:
  profiles:
    active: dev
  devtools:
    add-properties: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://kubernetes.local:30006/demo.wings
    username: developer
    password: developer
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 3
      minimumIdle: 1
      idleTimeout: 60000
      maxLifetime: 300000
  general-datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://kubernetes.local:3306/websap_general
    username: developer
    password: developer
  jpa:
    show-sql: false
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
        keep-alive: "10s"
    scheduling:
      thread-name-prefix: "jenjen-scheduller-"
      pool:
        size: 4

hibernate:
  hbm2ddl:
    auto: none

springdoc:
  swagger-ui:
    path: /docs

logging:
  level:
    web: 'INFO'

sap:
  enabled: false
  active-profile: "WM-AA01"
  implementation: db