server:
  port: 8000
  servlet:
    context-path: '/api'

spring:
  profiles:
    active: dev
  devtools:
    add-properties: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://kubernetes.local:30006/demo.wings
    username: developer
    password: developer
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 3
      minimumIdle: 1
      idleTimeout: 60000
      maxLifetime: 300000
  jpa:
    show-sql: false

springdoc:
  swagger-ui:
    path: /docs

logging:
  level:
    web: 'DEBUG'

sap:
  connection:
    sapClient: 100
    userID: user
    password: password
    language: EN
    host: 172.20.3.10
    systemNumber: 00
    r3name: SDV