server:
  port: 8000
  servlet:
    context-path: '/api'

spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/demo_wings
    username: root
    password:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 3
      minimumIdle: 1
      idleTimeout: 60000
      maxLifetime: 300000
  jpa:
    show-sql: false

logging:
  level:
    web: 'DEBUG'