server:
  port: 8000
  servlet:
    context-path: '/api'

spring:
  devtools:
    add-properties: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/demo_wings
    username: root
    password:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 3
      minimumIdle: 1
      idleTimeout: 60000
      maxLifetime: 300000
  general-datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/websap_general
    username: root
    password:
  jpa:
    show-sql: false

logging:
  level:
    web: 'DEBUG'

sap:
  connections:
    - connection-id: SAP-SMU
      sap-client: 110
      user-id: ${USER_SAP:abap05}
      password: ${PASSWORD_SAP:password0505}
      language: EN
      host: 172.20.3.10
      system-number: "00"
      r3name: SDV
      type: single

    - connection-id: SAP-AMG
      sap-client: 110
      user-id: ${USER_SAP:abap10}
      password: ${PASSWORD_SAP:password1010}
      language: EN
      host: 172.20.5.23
      system-number: "00"
      r3name: SDV
      type: pool
      min-pool: 3
      max-pool: 5